apiVersion: v1

kind: Pod

metadata:
  name: meupod

spec:
  containers:
    - name: meupod
      image: kubedevio/web-page:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80

---

apiVersion: v1

kind: Pod

metadata:
  name: meupod-label
  labels:
    name: web

spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
