apiVersion: apps/v1

kind: Deployment
metadata:
  name: meudeploymentwithservice

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: web
          image: kubedevio/web-page:green
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1

kind: Service

metadata:
  name: web

spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort
