version: '3.5'
services:
  angular:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
    ports:
      - '4200:4200'
      - '8080:8080'